name: 'data_analysis_starter'
version: '1.0.0'

profile: 'dbt'

model-paths: ["models"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  data_analysis_starter:
    staging:
      +materialized: table
    marts:
      +materialized: table
