version: "3"

includes:
  dbt:
    taskfile: ./taskfile.dbt.yml


tasks:
  dashboard:
    desc: Run the local Streamlit dashboard against dev.duckdb
    cmds:
      # Avoid having a lock on the dev database, because it inhibits development
      - cp ./data/dev.duckdb ./data/dashboard.duckdb
      - defer: rm ./data/dashboard.duckdb
      - uv run streamlit run dashboard.py --server.headless true
